name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: (Optional) List repository files for debugging
      - name: List repository files
        run: ls -R

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: (Optional) Clear any cache (if you have a script defined)
      #- name: Clear cache
      #  run: npm run clear

      # Step 6: Build the Docusaurus site
      - name: Build Docusaurus site
        run: npm run build

      # Step 7: Deploy the build folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.Docusaurus_TOKEN }}
          publish_dir: ./build
